### ISSUE TITLE
Are you going to post Spanish models?

### ISSUE THREAD

**Issue by chinshr** [facebookresearch/fairseq-lua#1]
It would be nice if there were any Spanish models available. Could you point me to them in case I missed? Thanks.

**Comment by jgehring** [comment]
We currently don't provide models for English to Spanish translation. However, we would be happy to include a list of community-built models for various language pairs in the repository. In terms of training data, the [2013 WMT translation task](http://www.statmt.org/wmt13/translation-task.html) included some Spanish data but I don't know the size of that corpus from the top of my head. Other (non-news) corpora may exist as well.
