### ISSUE TITLE
FairSeq model as a Server

### ISSUE THREAD

**Issue by mdasadul** [facebookresearch/fairseq-lua#104]
Is there any script available to use the trained model in server. I am aware of generate-line and generate.

Thanks

**Comment by jgehring** [comment]
No, we don't have a ready-made script for server-side translation. I'd recommend adapting `generate-lines` for your specific client-server setup. The dataset iterate in that script is a bit cumbersome but you can simply replace it by something else that calls the necessary functions as needed (following [generate-lines.lua#L108](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L108)), e.g.:

```lua
local text = ... -- wherever you get the source string from
local bin = tokenizer.tensorizeString(text, config.srcdict):view(-1, 1):int()
local sample = {
    source = bin
    sourcePos = data.makePositions(bin, config.srcdict:getPadIndex()):view(-1, 1),
    text = text,
    target = torch.IntTensor(1, 1),
    bsz = 1,
}
if config.aligndict then
    -- see generate-lines.lua#L129
end

local hypos, scores, attns = model:generate(config, sample, searchf)
-- ... and so son
```

**Comment by mdasadul** [comment]
Thanks @jgehring That's very helpful. I will give it a try

**Comment by mdasadul** [comment]
I make it working. Thanks for your help @jgehring . I have another question related to UNK. Is it possible to replace the UNK in hypothesis by using the source  when the model fails to generate one?

**Comment by jgehring** [comment]
Yes; we use an alignment dictionary for this. The corresponding script is at [scripts/unkreplace.lua](https://github.com/facebookresearch/fairseq/blob/master/scripts/unkreplace.lua) and is meant to be run on the output of `generate` (it parses the H- and A- lines, for example). The main loop over the hypotheses is at [unkreplace.lua#L79](https://github.com/facebookresearch/fairseq/blob/master/scripts/unkreplace.lua#L79-L105) and requires `hypos[i]`, `srcs[i]` and `attns[i]` to match.

The alignment dictionary can be generated with [scripts/makealigndict.lua](https://github.com/facebookresearch/fairseq/blob/master/scripts/makealigndict.lua), which in turn requires a  symmetric alignment of a parallel corpus generated with fast_align, e.g. by running [scripts/build_sym_alignment.py](https://github.com/facebookresearch/fairseq/blob/master/scripts/build_sym_alignment.py).

**Comment by mdasadul** [comment]
Thanks 
It's working nicely as a server but bit slow

**Comment by mdasadul** [comment]
I am working to to speed up by sending input as a batch instead one line at a time. I think I can use something like the dataset Iterator and Textfile Iterator is doing. My data is in a lua table. I am wondering to know how I can convert lua table to dataset iterator. I am trying to resuse the code from generate-lines.lua. Any help will be greatly appreciated @jgehring  
                

  ```lua
     local TextFileIterator, _ =
    torch.class('tnt.TextFileIterator', 'tnt.DatasetIterator', tnt)

TextFileIterator.__init = argcheck{
    {name='self', type='tnt.TextFileIterator'},
    {name='path', type='table'},
    {name='transform', type='function',
        default=function(sample) return{
									bin = binerization.tensorizeString(sample, config.srcdict),
									text = sample,
						} end},
    call = function(self, path, transform)
			function self.run()
				local fd=self.path
				
				print(self.path)
				
				--return function()
				print(#fd)
					for i =1,#fd do
						local line = fd[i]
						
						if line ~= nil then
							return transform(line)
							 --[[return {
									bin = binerization.tensorizeString(line, config.srcdict),
									text = line,
						}--]]
						end
					end
				--end 
			end
		end
}


local dataset = tnt.DatasetIterator{
    iterator = tnt.TextFileIterator{
        path,
        transform = function(line)
            return {
				
                bin = binerization.tensorizeString(line, config.srcdict),
                text = line,
            }
        end
    },
    transform = function(sample)
        local source = sample.bin:view(-1, 1):int()
       
 local sourcePos = data.makePositions(source,
            config.srcdict:getPadIndex()):view(-1, 1)
        local sample = {
            source = source,
            sourcePos = sourcePos,
            text = sample.text,
            target = torch.IntTensor(1, 1), -- a stub
        }
        if config.aligndict then
            sample.targetVocab, sample.targetVocabMap,
                sample.targetVocabStats
                    = data.getTargetVocabFromAlignment{
                        dictsize = config.dict:size(),
                        unk = config.dict:getUnkIndex(),
                        aligndict = config.aligndict,
                        set = 'test',
                        source = sample.source,
                        target = sample.target,
                        nmostcommon = config.nmostcommon,
                        topnalign = config.topnalign,
                        freqthreshold = config.freqthreshold,
                    }
        end
        return sample
    end,
}
local data = "He is going home. <eos> He is from Itly <eos>"
table_data = split(data)  -- convert data into table
print(table_data )
dataset.iterator.path = table_data 
for sample in dataset() do
	print(sample)
end 


```
