### ISSUE TITLE
out of memory at the end of epoch

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#108]
Hi,

I wonder whether there are things I can look into about the OOM issue. I sometimes got out of memory when it is in the end of an epoch and doing dev, test evaluation.  Sometimes it happens after checkpoints are saved and in the beginning of a new epoch. 
Will ``collectgarbage`` be helpful? I saw it in some parts of the code. What is the purpose of using it once or twice?
Thanks!

**Comment by michaelauli** [comment]
The two collectgarbage are because of resurrection: https://stackoverflow.com/questions/28320213/why-do-we-need-to-call-luas-collectgarbage-twice

I recently pushed a commit that should make the trainer more memory efficient.

**Comment by posenhuang** [comment]
Thanks a lot @michaelauli.
