### ISSUE TITLE
How convolution exactly works in this network?

### ISSUE THREAD

**Issue by aburkov** [facebookresearch/fairseq-lua#111]
Hi, 

I read the paper and cannot get how the convolution happens and how the dimensions are obtained.

The paper says "each convolution kernel is parametrized as W \in R^{2d \times kd} and takes as input X \in R^{k \times d} which is a concatenation of k input elements embedded in d dimensions and maps them to a single output element Y \in R^{2d}"

1) How can a kernel have a higher dimensionality than input? {2d \times kd} > {k \times d}?
2) How exactly it happens that the output of the application of one kernel to the input has the dimensionality of 2d? What equation is used to transform {k \times d} into 2d?
3) How a kernel moves over the input? What is the stride?
4) After one convolution applies to the input, what is the dimensionality of the convolved feature (feature map)?

Would be glad if someone could explain. I understand convolutions in case of images, but here I get lost.

Thanks!

**Comment by michaelauli** [comment]
1) The kernel maps k input elements of size d each. It does not operate over individual inputs but over k inputs. 
2) Given X \in R^{k \times d}, W \in R^{2d \times kd}, the mapping is WX = Y, where Y \in R^{2d}
3) The stride is one.
4) We pad the input such that we get as many outputs as inputs. For a sentence of n words, we first emebed it in dimension d, and the input to the first convolution is n x d, which outputs n x 2d features, then the GLU is applied which turns this into n x d and the next convolution is applied and so on.

Hope that helps.

**Comment by aburkov** [comment]
Thank you Michael. So basically such choice of kernel W is your design choice? Just like in the image processing the kernel always returns a scalar?

Why the kernel output is 2d. What is the intuition behind such choice?

**Comment by michaelauli** [comment]
It is a bit unusual that we increase the output frame size, i.e., map to 2d, however, the reason is so that we can use half of the outputs as gates in the GLU.

**Comment by aburkov** [comment]
Cool thank you!
