### ISSUE TITLE
Assertion in topk() failed during generation

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-lua#113]
hello,I meet a problem when I use fairseq generate-lines.
I just use 
 CUDA_VISIBLE_DEVICES=1 fairseq generate-lines -sourcedict data-bin/nmt/dict.in.th7 -targetdict data-bin/nmt/dict.ref.0.th7 -path trainings/second/model_best_opt.th7 -beam 10 -nbest 2

| [target] Dictionary: 3 types
| [source] Dictionary: 3 types
> 
/home/hfyu/package/torch/install/bin/luajit: ...ackage/torch/install/share/lua/5.1/fairseq/clib/init.lua:43: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...ackage/torch/install/share/lua/5.1/fairseq/clib/init.lua:43: in function 'topk'
	...u/package/torch/install/share/lua/5.1/fairseq/search.lua:323: in function 'prune'
	.../install/share/lua/5.1/fairseq/models/ensemble_model.lua:151: in function 'generate'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:218: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00406670

**Comment by travel-go** [comment]
I donnot know how to deal with it? please help me

**Comment by jgehring** [comment]
Hi @travel-go, your beam size for generation is larger than your dictionary. This will trigger an error in the `topk()` call. Can you try running with `-beam 1` or `-beam 3`? Also, why is your dictionary so small?

**Comment by travel-go** [comment]
Maybe my problem is the encoding format

**Comment by jgehring** [comment]
Do you still have the command arguments and log output of `fairseq preprocess`?

**Comment by travel-go** [comment]
In addition, I have a mistake in training problem 
/home/hfyu/package/torch/install/bin/luajit: ...age/torch/install/share/lua/5.1/fairseq/models/model.lua:339: bad argument #3 to 'narrow' (out of range at /home/hf    yu/package/torch/extra/cutorch/lib/THC/generic/THCTensor.c:446)
  3 stack traceback:
  4     [C]: in function 'narrow'
  5     ...age/torch/install/share/lua/5.1/fairseq/models/model.lua:339: in function 'updateMinMaxLenProb'
  6     ...age/torch/install/share/lua/5.1/fairseq/models/model.lua:280: in function 'generate'
  7     ...e/torch/install/share/lua/5.1/fairseq/torchnet/hooks.lua:192: in function <...e/torch/install/share/lua/5.1/fairseq/torchnet/hooks.lua:184>
  8     ...ge/torch/install/share/lua/5.1/fairseq/scripts/train.lua:448: in function 'runFinalEval'
  9     ...ge/torch/install/share/lua/5.1/fairseq/scripts/train.lua:466: in main chunk
 10     [C]: in function 'require'
 11     ...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
 12     [C]: at 0x00406670
~

**Comment by travel-go** [comment]
My coding format is utf-8, my corpus is Chinese translation into english, I do not know why my dictionary is so small.

this is my the command arguments and log output of fairseq preprocess.


 CUDA_VISIBLE_DEVICES=1 fairseq preprocess -sourcelang in -targetlang ref.0 -trainpref /home/hfyu/data-seq/nist00 -validpref /home/hfyu/data-seq/nist06 -testpref /home/hfyu/data-seq/nist03 -thresholdsrc 3 -thresholdtgt 3 -destdir data-bin/nist03
| [in] Dictionary: 3 types
| [in] /home/hfyu/data-seq/nist00.in: 1252976 sents, 29182243 tokens, 93.49% replaced by <unk>
| [in] /home/hfyu/data-seq/nist06.in: 1664 sents, 40013 tokens, 95.84% replaced by <unk>
| [in] /home/hfyu/data-seq/nist03.in: 919 sents, 25014 tokens, 96.33% replaced by <unk>
| [in] Wrote preprocessed data to data-bin/nist03
| [ref.0] Dictionary: 3 types
| [ref.0] /home/hfyu/data-seq/nist00.ref.0: 1252976 sents, 35761906 tokens, 95.82% replaced by <unk>
| [ref.0] /home/hfyu/data-seq/nist06.ref.0: 1664 sents, 48039 tokens, 96.54% replaced by <unk>
| [ref.0] /home/hfyu/data-seq/nist03.ref.0: 919 sents, 30241 tokens, 96.96% replaced by <unk>
| [ref.0] Wrote preprocessed data to data-bin/nist03

**Comment by jgehring** [comment]
This looks strange. The 3 types in the dictionary should be the standard items for `<pad>`, `<eos>` and `<unk>`; in other words, the pre-processing script did not pick up anything from the data. Can you maybe try to add some print statements to [`addFileToDictionary`](https://github.com/facebookresearch/fairseq/blob/master/fairseq/text/tokenizer.lua#L36) to better understand how lines are being tokenized and what words are added (or not added?) to the dictionary and run the preprocessing script again? If possible, you can also post a couple of lines of the parallel data and I can give it a go.

**Comment by travel-go** [comment]
I think there is a problem when I am in the preproecess, I use the corpus is translated into English, I see the bash prepare-iwslt14.sh,  Should I not have to run some orders before I run the preprocess?

**Comment by travel-go** [comment]
ok I find the -nwordstgt and -nwordssrc should be set ,and -thresholdsrc 3 -thresholdtgt 3 should be removed. Thank you very much .

**Comment by jgehring** [comment]
@travel-go the preprocessing with fairseq might be screwed up, though. With the `-threshold* n` options, all words which appear less than n times will be excluded from the dictionary. If this turns out to reject all words, there's something wrong with the script or your data.
