### ISSUE TITLE
Characters as input instead of words

### ISSUE THREAD

**Issue by riteshpanjwani** [facebookresearch/fairseq-lua#119]
How can I give one-hot character embedding as an input to the model instead of word embedding?
The input and output of the model is a sequence of characters. Something like this: https://arxiv.org/abs/1610.03017
I fed whitespace separated character sequences that are arranged line-by-line as source and target side data. The preprocessing step replaced huge portion of the data with unknown ('UNK') tag.

**Comment by jgehring** [comment]
You can either (externally) pre-process the data to look like `t h i s i s a p h r a s e .` or change the tokenization function to split lines into characters [here](https://github.com/facebookresearch/fairseq/blob/master/fairseq/text/tokenizer.lua#L26). You probably don't wan to use any thresholding for the preprocessing step and also increase the maximum sequence length beyond 1024 (grep for 1024 in the code).

**Comment by riteshpanjwani** [comment]
Thank you!
