### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by mzeidhassan** [facebookresearch/fairseq-lua#12]
Does this support translation from English into Arabic? What tokenizer do you use?

Can I still train a model using CPU or is GPU a must to use your toolkit?

Thanks,
Mohamed

**Comment by jgehring** [comment]
We have not trained any models on English-Arabic so far, but I can't think of anything that would make this more difficult than training on another language pair. fairseq does not include tokenization and pre-processing facilities, but the scripts from https://github.com/moses-smt/mosesdecoder and https://github.com/rsennrich/subword-nmt work very well. See [data/prepare-iwslt14.sh](https://github.com/facebookresearch/fairseq/blob/master/data/prepare-iwslt14.sh) for some example code for pre-processing.

You'll need a GPU for training a new model.
