### ISSUE TITLE
Any method to reduce GPU memory usage?

### ISSUE THREAD

**Issue by frankang** [facebookresearch/fairseq-lua#122]
The fairseq pytorch version consumes about 50% less GPU memory compared to the lua version, in both the training and inference process (and 40% faster during the inference, for a single sentence). Could you suggest some possible ways to reduce the memory? Thanks!

**Comment by michaelauli** [comment]
The lower memory usage of fairseq-py is due to releasing unused memory which is not the case for fairseq. The faster inference speed is due to vectorizing a bit more of the beam search code. I recommend using the pytorch version which has those improvements if possible.
