### ISSUE TITLE
Is Writing Prompts Dataset available in this repo ?

### ISSUE THREAD

**Issue by GBLin5566** [facebookresearch/fairseq-lua#127]
Hi,

In the paper [Hierarchical Neural Story Generation](https://arxiv.org/abs/1805.04833), the authors said they collected the hierarchical story generation dataset from Reddit’s WRITINGPROMPTS forum and attached the link to this repo. However, I could not find the dataset in this repo, I'm wondering if the dataset is available here. Thanks !

**Comment by hmc-cs-mdrissi** [comment]
It can be found in the other [fairseq](https://github.com/pytorch/fairseq) repo (the PyTorch one).
