### ISSUE TITLE
Cannot reverse order of translation

### ISSUE THREAD

**Issue by andrewb-ms** [facebookresearch/fairseq-lua#128]
This works (EN -> DE):

fairseq generate-lines -path wmt14.en-de.fconv-float/model.th7 -sourcedict wmt14.en-de.fconv-float/dict.en.th7 \
    -targetdict wmt14.en-de.fconv-float/dict.de.th7 -beam 5

But this does not (DE -> EN):

fairseq generate-lines -path wmt14.en-de.fconv-float/model.th7 -sourcedict wmt14.en-de.fconv-float/dict.de.th7 \
    -targetdict wmt14.en-de.fconv-float/dict.en.th7 -beam 5

Is that expected?

**Comment by jgehring** [comment]
Yes, that's expected. The "en-de" model can only translate from English to German as it was trained on such sentence pairs exclusively.

**Comment by andrewb-ms** [comment]
Got it, thanks.  Do you happen to have any pretrained models where the destination language is English?

**Comment by jgehring** [comment]
Not that I know of, but maybe it's worth asking in https://www.facebook.com/groups/fairseq.users?
