### ISSUE TITLE
Is it possible to modify this model for classification purpose

### ISSUE THREAD

**Issue by lliu25** [facebookresearch/fairseq-lua#13]
I was wondering if it is possible to modify such efficient seq2seq model to a classification task? If is, what would be a general guideline for such purpose? Thanks!

**Comment by michaelauli** [comment]
Yes, this should be possible but you may also want to take a look at fastText which was built for this use case: https://github.com/facebookresearch/fasttext

**Comment by sheerun** [comment]
@michaelauli Isn't fasttext limited to reasoning from bag of words? Would it work if sequence of words is important?

**Comment by michaelauli** [comment]
I believe this is true but it probably does not hurt to use fasttext as a baseline.
