### ISSUE TITLE
Unable to Download Pretrained models

### ISSUE THREAD

**Issue by nithya4** [facebookresearch/fairseq-lua#133]
curl https://s3.amazonaws.com/fairseq-py/models/wmt14.v2.en-fr.fconv-py.tar.bz2 gives me a 
"NoSuchBucket" error.

Is there somewhere else I can access the pretrained models?

**Comment by myleott** [comment]
Here is the new path: http://dl.fbaipublicfiles.com/fairseq/models/wmt14.v2.en-fr.fconv-py.tar.bz2. We'll update the README shortly.

**Comment by nithya4** [comment]
Thanks.
