### ISSUE TITLE
Inference/finetuning  Blender in fairseq

### ISSUE THREAD

**Issue by hckh** [facebookresearch/fairseq-lua#144]
The blender paper (https://parl.ai/projects/recipes/) says that the models were originally trained in fairseq, but they are released as parl.ai models. 

Is it possible to perform inference on the released models and finetune tune them in fairseq? 

I could imagine the following pipeline:

- tokenize data for finetuning with https://github.com/huggingface/tokenizers (using ByteLevelBPETokenizer, and model.dict-merges.txt)
- convert model.dict-vocab.json to a space separated file, and use that and the tokenized data to run fairseq-preprocess
- run inference or finetuning

should this work, or is there some way this could be "silently wrong"

Thanks!

**Comment by jgehring** [comment]
The paper you mention is surely using [the PyTorch version of fairseq](https://github.com/pytorch/fairseq) which is under active development. It would be best to post your question there.

**Comment by hckh** [comment]
Thanks, not sure how I accidentally ended up here.
