### ISSUE TITLE
[question] how to know use which arch parameters?

### ISSUE THREAD

**Issue by HyejinWon** [facebookresearch/fairseq-lua#145]
Hello,

I wonder how to know --arch some_model has parameter?

Example, When I used '--arch fconv', is there a way to figure out which parameters to list after?

**Comment by jgehring** [comment]
This concerns the Python version of fairseq, right? It would best to post this issue at [pytorch/fairseq](https://github.com/pytorch/fairseq).

**Comment by HyejinWon** [comment]
No, I mean command line version of fairseq. 
How do I know what parameters to put in your existing model(such as fconv, transformer ..etc.) for a train?

**Comment by jgehring** [comment]
I understand, but this repo contains the Lua version of fairseq, and the CLI scripts do not offer an `--arch` parameter.

**Comment by HyejinWon** [comment]
Ah! Thank you. I  was confused.
