### ISSUE TITLE
Test Cases failing ?

### ISSUE THREAD

**Issue by iamsimha** [facebookresearch/fairseq-lua#19]
Hi
When I execute
```lua
lua test/test.lua
```
The test cases shown in the image are failing. Can you please let me know if I am doing something wrong?

![image](https://cloud.githubusercontent.com/assets/3105044/25946584/6b4b2cf8-3669-11e7-8da6-649783f2ac6d.png)

**Comment by jgehring** [comment]
Could you post the error tracebacks that normally follow afterwards?

**Comment by iamsimha** [comment]
All the failed test cases fail at the same place.

![image](https://cloud.githubusercontent.com/assets/3105044/25947369/d318f6f0-366c-11e7-98a5-11858bd59834.png)

**Comment by jgehring** [comment]
This is caused by https://github.com/torch/tds/issues/25. I'd recommend using luajit for the time being.
