### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by minmummax** [facebookresearch/fairseq-lua#24]
when i run airseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 \-targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
i get error 
Tried loading libnccl.so.1 but got error /home/actl/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
Tried loading libnccl.1.dylib but got error /home/actl/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
why?

**Comment by shahbazsyed** [comment]
@minmummax I think you are missing the nccl library. Do the following steps to install it: 

``` 
git clone https://github.com/NVIDIA/nccl
cd nccl
make install
sudo ldconfig
luarocks install nccl
```
Hope it helps.

**Comment by guotong1988** [comment]
Thank you @shahbazsyed .
I have done your commands. But when I run `train.lua` in the zbstudio, I still get error:
```
Tried loading libnccl.1.dylib but got error /home/gt/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.1.dylib: cannot open shared object file: No such file or directory
Tried loading libnccl.so.1 but got error /home/gt/torch/install/share/lua/5.1/nccl/ffi.lua:192: libnccl.so.1: cannot open shared object file: No such file or directory
```

**Comment by guotong1988** [comment]
find libnccl.so* and add the directory to LD_LIBRARY_PATH

**Comment by PratsBhatt** [comment]
I am still facing this issue even after adding the directory to the LD_LIBRARY_PATH. Any help is appreciated :) Thank you in advance.

**Comment by jekbradbury** [comment]
Occasionally you have to manually create symlinks for libnccl.so.1 -> libnccl.so
