### ISSUE TITLE
Can I only use CPU to debug and understand it?

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/fairseq-lua#25]
I don't want to train a whole model and predict. I only want to understand it. Is it possible to debug it, only using CPU without GPU? 
Thank you!

**Comment by jgehring** [comment]
The CPU and GPU models have identical modules and structure for fconv, i.e. for all pre-trained models. What prevents them from being trained on the CPU is the custom Torchnet engine we're using (which makes use of nccl). Did you have anything specific to debug in mind?

**Comment by guotong1988** [comment]
No, I don't have anything specific to debug.
I will study it on GPU.
Hope we could debug all of it on CPU in the future.

**Comment by guotong1988** [comment]
Oh, it seems I could try to install cuda and try, as my notebook support cuda.

**Comment by jgehring** [comment]
For training, you might be able to make it work by removing nccl and cutorch-related calls in [fairseq/torchnet/ResumableDPOptimEngine.lua](https://github.com/facebookresearch/fairseq/blob/master/fairseq/torchnet/ResumableDPOptimEngine.lua) but I have not tested this. However, you can just fire up th, `require 'fairseq'` and load a model with `torch.load` if you want to take a closer look at it.
