### ISSUE TITLE
Missing dependencies for fairseq

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fairseq-lua#29]
When launching the install with ` luarocks make rocks/fairseq-scm-1.rockspec` I get 

```
Missing dependencies for fairseq:
rnnlib 
torchnet 
visdom 
torchnet-sequential 
nccl 
tbc 
tds
```

Will the install script adding those dependencies automatically?

**Comment by jgehring** [comment]
Yes, right after that message `luarocks` will install those dependencies.

**Comment by loretoparisi** [comment]
ok so closing this! thanks.
