### ISSUE TITLE
fairseq-scm-1.rockspec file not found

### ISSUE THREAD

**Issue by micsanMercy16** [facebookresearch/fairseq-lua#32]
Hello, I am trying to use fairseq and I run into this issue, please advise

micheles-mba:fairseq.git micheles$ luarocks make rocks/fairseq-scm-1.rockspec --local

Error: File not found: rocks/fairseq-scm-1.rockspec
micheles-mba:fairseq.git micheles$ ls
branches		trunk
fairseq.git		wmt14.en-fr.fconv-cuda
micheles-mba:fairseq.git micheles$

**Comment by jgehring** [comment]
Your local checkout seems to be borked. How did you clone the repository?

**Comment by micsanMercy16** [comment]
Hello Jonas, Thank you for your reply. I also cloned it on github and here is the message returned once I try to commit 
micheles-mba:torch micheles$ git commit -m https---github.com-facebookresearch-fairseq.git

On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	modified:   exe/luajit-rocks (modified content)

Untracked files:
	cunn/
	fairseq.git/
	rocks.git/

no changes added to commit

Please advice. Thank you.

**Comment by jgehring** [comment]
Something went wrong when you attempted to clone the repository, e.g. I'm not sure where the *.git folders come from. Try this in a different directory:

```
$ git clone https://github.com/facebookresearch/fairseq.git
$ cd fairseq
$ luarocks make rocks/fairseq-scm-1.rockspec
```

**Comment by micsanMercy16** [comment]
Thank you so much Jonas. It is almost fine now. Only draw back is the following

micheles-mba:fairseq micheles$ luarocks make rocks/fairseq-scm-1.rockspec

Error: Your user does not have write permissions in /usr/local 
-- you may want to run as a privileged user or use your local tree with --local.
micheles-mba:fairseq micheles$ 

Please advise. Cheers

**Comment by micsanMercy16** [comment]
And when I try adding --local here is the result
micheles-mba:fairseq micheles$ luarocks make rocks/fairseq-scm-1.rockspec

Error: Your user does not have write permissions in /usr/local 
-- you may want to run as a privileged user or use your local tree with --local.
micheles-mba:fairseq micheles$ luarocks make rocks/fairseq-scm-1.rockspec --local

Missing dependencies for fairseq:
tds 
cudnn 
visdom 
nngraph 
penlight 
nccl 
torch >= 7.0
rnnlib 
torchnet 
threads 
tbc 
cunn 
torchnet-sequential 
argcheck 
lua-cjson 


Error: Could not satisfy dependency: tds 
micheles-mba:fairseq micheles$ 

Thank you again.

**Comment by jgehring** [comment]
Maybe try from a local torch installation? http://torch.ch/docs/getting-started.html provides a nice tutorial for this.

**Comment by micsanMercy16** [comment]
Ok better still now lua and cmake fail
micheles-mba:torch micheles$ ./install.sh
Prefix set to /Users/micheles/torch/install
Installing Lua version: LUAJIT21
CMake Error at exe/luajit-rocks/CMakeLists.txt:49 (ADD_SUBDIRECTORY):
  add_subdirectory given source "luarocks" which is not an existing
  directory.

Please advise. Merci, Danke

**Comment by jgehring** [comment]
Sorry, I can't help provide much help in this case. According to the error message, a subdirectory is not existing. Is the subdirectory really missing? Your checkout may be messed up again. For reference, this is the output I get for `git clone https://github.com/torch/distro.git torch --recursive`: https://gist.github.com/jgehring/c5db04113a5cc2e1afd9567b3648bc69.

**Comment by micsanMercy16** [comment]
Jonas, I followed your indications however another error appeared
micheles-mba:torch micheles$ luarocks make rocks/fairseq-scm-1.rockspec

Error: Your user does not have write permissions in /usr/local 
-- you may want to run as a privileged user or use your local tree with --local.
micheles-mba:torch micheles$ luarocks make rocks/fairseq-scm-1.rockspec --local

Error: File not found: rocks/fairseq-scm-1.rockspec
Thank you

**Comment by jgehring** [comment]
What's the output of `which luarocks`?

**Comment by micsanMercy16** [comment]
Hi Jonas, luarocks was missing and creating a hidden directory. So I ran bash install.sh on torch that has installed cutorch. Right now the output is /usr/local/bin/luarocks. However I am still installing and building NVCC. So after this step I will repeat which luarocks and share the output with you. Thank you!

**Comment by micsanMercy16** [comment]
Issue fixed, Jonas, thanks to my developer and colleague Casey Carter!

micheles-mba:trunk micheles$ luarocks make rocks/fairseq-scm-1.rockspec

Missing dependencies for fairseq:
rnnlib 
torchnet 
visdom 
torchnet-sequential 
nccl 
tbc 
tds 

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/rnnlib-0.1-1.rockspec... switching to 'build' mode
Cloning into 'torch-rnnlib'...
remote: Counting objects: 56, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 56 (delta 5), reused 33 (delta 4), pack-reused 0
Unpacking objects: 100% (56/56), done.
........
