### ISSUE TITLE
help me unable to convert argument 2 from cdata<int

### ISSUE THREAD

**Issue by ytgcljj** [facebookresearch/fairseq-lua#33]
lenovo1601@lenovo1601-Lenovo:~/fairseq$ fairseq preprocess -sourcelang de -targetlang en   -trainpref $TEXT/train -validpref $TEXT/valid -testpref $TEXT/test   -thresholdsrc 3 -thresholdtgt 3 -destdir data-bin/iwslt14.tokenized.de-en
/home/lenovo1601/torch/install/bin/lua: unable to convert argument 2 from cdata<int (*)(struct tds_elem_*, struct tds_elem_*)> to cdata<int (*)(const struct tds_elem_*, const struct tds_elem_*)>
stack traceback:
	[C]: in function 'tds_vec_sort'
	/home/lenovo1601/torch/install/share/lua/5.2/tds/vec.lua:98: in function 'sort'
	.../torch/install/share/lua/5.2/fairseq/text/Dictionary.lua:79: in function 'finalize'
	...1/torch/install/share/lua/5.2/fairseq/text/tokenizer.lua:79: in function <...1/torch/install/share/lua/5.2/fairseq/text/tokenizer.lua:74>
	(...tail calls...)
	...rch/install/share/lua/5.2/fairseq/scripts/preprocess.lua:110: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: in ?

**Comment by jgehring** [comment]
Aare you using Lua 5.2? This looks like the following issue in tds: torch/tds#25. As there is no fix for this yet, I suggest switching to luajit for the time being.

**Comment by ytgcljj** [comment]
@jgehring  
    thank you  .I'll try

**Comment by smolendawid** [comment]
@jgehring How to switch to luajit?

**Comment by guillaumekln** [comment]
To update this issue, this has been fixed in `tds`. You just need to update the package:

```
luarocks install tds
```
