### ISSUE TITLE
Install on macOS CPU

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fairseq-lua#36]
Despite fairseq installation on ubuntu/docker takes time, it works pretty straight forward, on `macOS` (CPU only) it can be very complicated through `luarocks`, due to a lot of dependencies,  so I'm putting [here](https://gist.github.com/loretoparisi/d8a1afa119ed98ae780922599f4ce9f2) this gist with all dependencies to install to get it working. Hope this helps!

**Comment by jgehring** [comment]
Thanks, but `luarocks` should take care of installing all dependencies automatically. Did a simple `luarocks make rocks/fairseq-cpu-scm-1.rockspec` not work for you?

**Comment by loretoparisi** [comment]
@jgehring Nope, there are several issues, starting with `torch` itself (the install script does not append to `.bash_profile` the `/torch/install/bin` folder). For some reason, despite of this, it tries to use system `luarocks` instead of the torch on `/torch/install/bin` (this issue is referenced on `torch` and `torch-nn` libraries. Solved those ones, not all the dependencies were resolved like `visdom`, `luasocket`, `tbd`, `moses` etc. In most of cases I had a resolve error from the install script (at the first error it exits). So I had to go one-by-one. The error was `Could not satisfy dependency: moses` (by example), etc. In the other way, I ended up with a working installation!

**Comment by jgehring** [comment]
In theory you can also do a system-wide installation of Luajit and torch. However, a default installation of `luarocks` will not include the torch-specific repository at https://github.com/torch/rocks. This is automatically being set up if you install torch/luajit-rocks (see the notes [here](https://github.com/torch/luajit-rocks#whats-the-point)). I think this can also be done manually by editing `/etc/luarocks/config.lua` to include the relevant bits [from here](https://github.com/torch/luajit-rocks/blob/master/luarocks/src/luarocks/config.lua.in).

**Comment by loretoparisi** [comment]
@jgehring Thank you, closing this, since it was more an hint that a real issue!
