### ISSUE TITLE
Error: Could not satisfy dependency: torch >= 7.0 and using only CPU no GPU compatible

### ISSUE THREAD

**Issue by micsanMercy16** [facebookresearch/fairseq-lua#40]
Hi Jonas,

Please advise the following and also the fact that I have a GPU but is Intel and not Nvidia. So I am running into issues. Thank you.

micheles-mba:fairseq micheles$ luarocks make rocks/fairseq-cpu-scm-1.rockspec --local

Missing dependencies for fairseq-cpu:
torch >= 7.0
lua-cjson 
rnnlib 
torchnet-sequential 
visdom 
torchnet 
argcheck 
tbc 
threads 
tds 
nngraph 

Error: Could not satisfy dependency: torch >= 7.0
micheles-mba:fairseq micheles$

**Comment by shahbazsyed** [comment]
@micsanMercy16 Did you try installing Torch and the nn packages before trying to install fairseq?

**Comment by micsanMercy16** [comment]
Hi Shahbaz, Yes. Anyway I have removed torch and reinstalled it along with nn . NOw I get the following message
micheles-mba:fairseq micheles$ fairseq generate-lines -path wmt14.en-fr.fconv-float/model.th7 -sourcedict wmt14.en.fr.fconv-float/dict.en.th7 \ -targetdict wmt14.en-fr.fconv-float/dict.fr.th7 -beam 5
THCudaCheck FAIL file=/Users/micheles/torch/extra/cutorch/lib/THC/THCGeneral.c line=66 error=35 : CUDA driver version is insufficient for CUDA runtime version

Please advise. Thank you.

**Comment by jgehring** [comment]
Hi @micsanMercy16, you cannot use CUDA functionality on a non-NVidia GPU. How did you manage to install cutorch? Anyway, I'd suggest remove CUDA-related torch packages from your installation (e.g. `luarocks remove cutorch` and so on).

**Comment by micsanMercy16** [comment]
HI Jonas. Could I still use fairseq just using CPU? Thank you.

**Comment by micsanMercy16** [comment]
Hi Jonas. It seems the model is responding. You should remove the \ from code page to test model.
you have on code page $ fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7 \
    -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5

In fact, I get 
micheles-mba:fairseq micheles$ fairseq generate-lines -path wmt14.en-fr.fconv-float/model.th7 -sourcedict wmt14.en-fr.fconv-float/dict.en.th7 -targetdict wmt14.en-fr.fconv-float/dict.fr.th7 -beam 5 
| [target] Dictionary: 44666 types
| [source] Dictionary: 44409 types
> why this took so long ?
S	why this took so long ? 
O	why this took so long ?
H	-0.3566732108593	Pourquoi cela a-t-il pris tant de temps ? 
A	1 1 3 3 5 5 5 5 7


Thank you for your help and I hope my errors and your fixing helped out a bit. Danke!

**Comment by micsanMercy16** [comment]
Lemme know if you need help with other languages dictionaries. I will gladly help your team pointing out dictionaries and corpora in up to 25 languages for free or also to localize for the benefit of FB and Fairseq. Delighted to have interacted with you Jonas and your team
https://www.linkedin.com/in/michelesantamaria/
micheles@telenav.com

**Comment by jgehring** [comment]
> You should remove the \ from code page to test model.

Sorry for the confusion -- the backslash is there because the command in the README is split over multiple lines and this usually requires escaping the newline characters. Depending on your setup, copy-pasting the command might not work as expected.
