### ISSUE TITLE
The gpu memory of M40 as the paper reported is 12GB or 24GB?

### ISSUE THREAD

**Issue by StillKeepTry** [facebookresearch/fairseq-lua#41]
I try to product the experiment result as the paper reported on K40 (12GB) , but i find i can't set the batch size as much as the paper reported like 48 in wmt14 en-ge?

**Comment by jgehring** [comment]
Are you using the parameters listed in the README.md of the pre-trained model (it was recently added to the tarballs)?

**Comment by StillKeepTry** [comment]
I find it, thank you.
This is our train parameters:
` fairseq train -sourcelang en -targetlang de -datadir data-bin/wmt15.en-de -model fconv -nenclayer 15 -nlayer 15 -fconv_nhids 512,512,512,512,512,512,512,512,512,512,768,768,768,20    48,2048 -fconv_nlmhids 512,512,512,512,512,512,512,512,512,512,768,768,768,2048,2048 -fconv_kwidths 3,3,3,3,3,3,3,3,3,3,3,3,3,1,1 -fconv_klmwidths 3,3,3,3,3,3,3,3,3,3,3,3,3,1,1 -dropout     0.2 -optim nag -lr 0.25 -clip 0.1 -momentum 0.99 -timeavg -bptt 0 -savedir trainings/fconv_en-de_15 -validbleu -batchsize 48`

**Comment by michaelauli** [comment]
You also need to set -maxbatch to limit the maximum number of tokens in a batch so that you do not run out of memory for batches with long sentences. For the WMT14 en-de BPE model we used -maxbatch 1200 - see the README again.
