### ISSUE TITLE
Error：...../torch/install/share/lua/5.1/torch/init.lua:102: class nn.ZipTable has been already assigned a parent class

### ISSUE THREAD

**Issue by tobyyouup** [facebookresearch/fairseq-lua#42]
When I install torch following http://torch.ch/docs/getting-started.html, and fairseq, and run fairseq generate-lines  command, it comes this error. 

fairseq generate-lines -path wmt14.en-fr.fconv-cuda/model.th7 -sourcedict wmt14.en-fr.fconv-cuda/dict.en.th7     -targetdict wmt14.en-fr.fconv-cuda/dict.fr.th7 -beam 5
/home/torch/install/bin/luajit: /home/torch/install/share/lua/5.1/torch/init.lua:102: class nn.ZipTable has been already assigned a parent class

stack traceback:
        [C]: in function 'newmetatable'
        /home/torch/install/share/lua/5.1/torch/init.lua:102: in function 'class'
        .../torch/install/share/lua/5.1/rnnlib/nn/ZipTable.lua:12: in main chunk
        [C]: in function 'require'
        /home/torch/install/share/lua/5.1/rnnlib/init.lua:34: in main chunk
        [C]: in function 'require'
        ...h/install/share/lua/5.1/fairseq/models/avgpool_model.lua:18: in main chunk
        [C]: in function 'require'
        .../torch/install/share/lua/5.1/fairseq/models/init.lua:15: in main chunk
        [C]: in function 'require'
        /home/torch/install/share/lua/5.1/fairseq/init.lua:14: in main chunk
        [C]: in function 'require'
        ...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:15: in main chunk
        [C]: in function 'require'
        ...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
        [C]: at 0x00406670 

How could I solve this problem？

**Comment by jgehring** [comment]
It looks like `ZipTable` has just been added to nn (this commit is from yesterday: https://github.com/torch/nn/commit/78f9a498a6e5444eedc04fc670a2ab108ef1511d) while it is also present in torch-rnnlib. This has to be fixed in torch-rnnlib; for the time being, either use a version of nn prior to that commit or comment out `require 'rnnlib.nn.ZipTable'` in rnnlib's `init.lua` (mine is in ~/torch/install/share/lua/5.1/rnnlib/init.lua).

**Comment by tobyyouup** [comment]
@jgehring   thanks, problem solved!

**Comment by jgehring** [comment]
This should be fixed by facebookresearch/torch-rnnlib#6.

**Comment by mendadala** [comment]
Please help! I am getting this error.

/Users/mars/torch/install/bin/luajit: /Users/mars/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/mars/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/mars/torch/install/share/lua/5.1/hdf5/ffi.lua:56: ')' expected near '_close' at line 1437
stack traceback:
	[C]: in function 'error'
	/Users/mars/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:6: in main chunk
	[C]: in function 'dofile'
	...mars/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x010e18ea10

**Comment by jgehring** [comment]
Hi @mendadala, this does not seem to be related to the issue at hand. I'd recommend reaching out to the developers of the hdf5 module that you installed. I've found https://github.com/deepmind/torch-hdf5 but I'm not sure if that's the one you're using.
