### ISSUE TITLE
Out of memory error with data from opensubtitle.org

### ISSUE THREAD

**Issue by cozec** [facebookresearch/fairseq-lua#43]
Data: downloaded de-en pair from opensubtitles.org. About 13M sentence.

Train: same as provided in the readme.md
fairseq train -sourcelang de -targetlang en -datadir data-bin/iwslt14.tokenized.de-en \
  -model fconv -nenclayer 4 -nlayer 3 -dropout 0.2 -optim nag -lr 0.25 -clip 0.1 \
  -momentum 0.99 -timeavg -bptt 0 -savedir trainings/fconv

Machine: Amazon EC2 instance with 8GPU each 12G memory

Error: memory error.

Which parameter I can change without loss of accuracy?

**Comment by shahbazsyed** [comment]
You can try with the -batchsize option hopefully. The default value is 32, try a lower value like 16 and see if it helps.

**Comment by frutsy007** [comment]
Can you hell with the code

**Comment by shahbazsyed** [comment]
@frutsy007 
[Here ](https://github.com/facebookresearch/fairseq/blob/master/train.lua#L55)is the relevant line from the train.lua 

So in the train command mentioned in the readme.md you just add another option -batchsize 16 

Is this what you asked for?

**Comment by cozec** [comment]
I did:
1. cut half of the data
2. add: -maxbatch 1200 -batchsize 32 

so far it's running well. looks slower

**Comment by cozec** [comment]
Update:
the training fished after epoch 15. See below for the terminal output. There is out of memory error for beam 20. I did notice that during decoding, only 1 out of 8 gpus is running. Two questions:

1. How to make use of all gpu for decoding?
2. If I want to do generation myself, which model shall I use? model_epoch15.th7 or model_best.th7?


| checkpoint 015 | epoch 015 | 0272400 updates | validloss     2.84 | valid ppl     7.18 | testloss     3.49 | test ppl    11.25
| checkpoint 015 | epoch 015 | 0272400 updates | saved model to trainings/fconv/model_epoch15.th7
| epoch 100 | 0272400 updates | 0000000 epoch updates | path trainings/fconv/state_epoch100.th7
| epoch 100 | 0272400 updates | 0000000 epoch updates | path trainings/fconv/state_last.th7
| epoch 100 | 0272400 updates | 0000000 epoch updates | path trainings/fconv/state_last.th7
| Test with beam=1: BLEU4 = 18.41, 45.0/23.5/13.6/8.0 (BP=1.000, ratio=0.834, sys_len=157319, ref_len=131141)
| Test with beam=5: BLEU4 = 23.91, 54.6/30.0/18.1/11.0 (BP=1.000, ratio=0.989, sys_len=132566, ref_len=131141)
| Test with beam=10: BLEU4 = 24.36, 55.8/30.8/18.7/11.5 (BP=0.988, ratio=1.012, sys_len=129582, ref_len=131141)
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6742/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/mnt/extra-storage/Projects/torch/install/bin/luajit: ...ge/Projects/torch/install/share/lua/5.1/nn/Container.lua:67:

**Comment by shahbazsyed** [comment]
You can use the [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) option to use all gpus for generating. Beam size of 20 is probably too large in my opinion. So if you can work with a lower beam size , it would avoid such out of memory errors. That was my experience from using other sequence to sequence frameworks.

**Comment by shahbazsyed** [comment]
About which model to use, I have never used it myself so far but the usual scenario is to use the model with lowest validation perplexity value.

**Comment by michaelauli** [comment]
batchsize 32 is not that large. Did you check how long your sequences are? You may have a few sentences that are very long which cause the OOM error - setting maxbatch will help but you also want to make sure you make good use of the GPU. Also make sure nothing else is running on the GPU.

**Comment by cozec** [comment]
I guess it's the answer i was looking for. Did a quick check, most of the sentences are less than 300. But the maximum length is 520.

Under this case, shall I set -maxbatch 300 or shall I remove those long sentence from training set?

**Comment by michaelauli** [comment]
I'd remove a sentence of length 520, it's probably not a single sentence anymore when it's that long.
-maxbatch 300 is probably too aggressive. If you have sequences that are 200-300 words long, then you will never reach the full batch size you specified. Maxbatch settings that split only a fraction of the batches work well, e.g., if <75% of sequences are no longer than 40 words, then choose maxbatch = 40 * batchsize; otherwise increase the batch size.

Try larger and larger settings, monitor the memory usage on the GPU and stick with a value that does not lead to OOM but still makes good use of the GPU.

**Comment by cozec** [comment]
After reducing batchsize to 32, the training is going well. There is an error during test for beam=10:

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6742/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/mnt/extra-storage/Projects/torch/install/bin/luajit: ...storage/Projects/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-6742/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
        [C]: in function 'v'
        ...storage/Projects/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'LogSoftMax_updateOutput'

How to fix it? I remember sb in the board said that beam=10 is not too big.

**Comment by michaelauli** [comment]
What batchsize do you use for generation? Try reducing it. Also, use -fastconv to make generation faster and to save some memory.

**Comment by cozec** [comment]
**It happens at the end of training.** 

The test goes well for beam=1 and 5

| Test with beam=1: BLEU4 = 25.39, 55.9/31.5/19.4/12.1 (BP=1.000, ratio=0.971, sys_len=135043, ref_len=131141)
| Test with beam=5: BLEU4 = 27.83, 62.4/36.5/23.2/14.9 (BP=0.934, ratio=1.069, sys_len=122719, ref_len=131141)

My training command is:

fairseq train -sourcelang de -targetlang en -datadir data-bin/opensub.tokenized.de-en \
  -model fconv -nenclayer 4 -nlayer 3 -dropout 0.2 -optim nag -lr 0.25 -clip 0.1 \
  -momentum 0.99 -timeavg -bptt 0 -savedir trainings/fconv -maxbatch 1200 -batchsize 32

Thanks a lot for your patience.

**Comment by michaelauli** [comment]
If you saved the model, then just run generate with a larger beam. There is a better chance it will work, because the trainer allocates memory both for training and generation. If you just do generation, it is likely that you can run with a larger beam.

**Comment by cozec** [comment]
Did as you suggested and it works for both beam=10 and beam=20!

One issue found:
1. In the test part of the training script, beam=5: BLEU4 = 27.83
2. saved the model, then test with.      , beam=5: BLEU4 = 26.12

The generate command is:
fairseq generate -sourcelang de -targetlang en -datadir data-bin/opensub.tokenized.de-en -dataset test -path trainings/fconv/model_best.th7 -beam 5 -batchsize 128 | tee /tmp/gen.out

Is it the expected result or sth wrong?

**Comment by michaelauli** [comment]
Please try with the last model file that was saved. The trainer evaluates
with the last model before convergence. model_best.th7 is the model that
achieved the best validation loss.

**Comment by cozec** [comment]
generate with last model
beam=5: BLEU4 = 26.19

It's still worse than "BLEU4 = 27.83". Sth wrong?

generate command:
fairseq generate -sourcelang de -targetlang en -datadir data-bin/opensub.tokenized.de-en -dataset test -path trainings/fconv/model_epoch17.th7 -beam 5 -batchsize 128 | tee /tmp/gen.out

**Comment by michaelauli** [comment]
What about the maxlen parameter? In the trainer it is set to 200, the default for generate is 500. Try setting it to the same value in generate.

**Comment by cozec** [comment]
Set -maxlen 200 and use model_best.th7 get the same result as in last training.
beam=5: BLEU4 = 27.83

thank you for all the help.

**Comment by michaelauli** [comment]
Ah yes, the final test eval in the trainer actually loads model_best.th7 - contrary to what I said earlier.

**Comment by frutsy007** [comment]
Facebook
