### ISSUE TITLE
is this is the right to use dropout

### ISSUE THREAD

**Issue by phveneno** [facebookresearch/fairseq-lua#44]
I want to use dropout in the training. I read the file train.lua. I found that add "-dropout 0.25" in the this command line.
fairseq train -sourcelang de -targetlang en -datadir data-bin/iwslt14.tokenized.de-en \
  -model fconv -nenclayer 4 -nlayer 3 -dropout 0.2 -optim nag -lr 0.25 -clip 0.1 \
  -momentum 0.99 -timeavg -bptt 0 -savedir trainings/fconv **-dropout 0.25**

is this is the right way?

**Comment by jgehring** [comment]
I'm not sure what you're asking exactly, but in your command-line `-dropout` appears twice now. If you do it like this, the final value will be 0.25 (i.e. the value used when the option was present last).

If you check `train.lua`, you'll notice that `-dropout` is a helper flag that can be used to set the remaining dropout flags (see [train.lua#L107-110](https://github.com/facebookresearch/fairseq/blob/master/train.lua#L107-L110)). There are 4 command-line flags for dropout and models are more or less free to implement them or not. The `fconv` model you're using implements all four. They have the following meaning:
- `-dropout_src` is for the source language embeddings, i.e. the LookupTable output
- `-dropout_tgt` is for the target language embeddings (the decoder input), i.e. the LookupTable output
- `-dropout_out` is for the decoder output *before* the final layer (which is embed size -> target vocab size)
- `-dropout_hid` is applied between single layers of the whole model. This is model-specific, but for the `fconv` model, dropout is applied to the input of each convolutional block.

**Comment by phveneno** [comment]
@jgehring thanks very much.  I don't see the dropout option in the example command-line.
