### ISSUE TITLE
Pretrained: the H evaluation is not in the TARGET language

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fairseq-lua#45]
For some text, the hypothesis H for the target language (FR), is in the source language (EN):

```
S	<unk> <unk> for me , 
O	nobody pray for me ,  
H	-1.7627129554749	I feel that my return is wrong . 
A	1 1 1 2 1 6 6 6 6
```

The execution args were

```
 [ 'generate-lines',
  '-path',
  '/root/wmt14.en-fr.fconv-float/model.th7',
  '-sourcedict',
  '/root/wmt14.en-fr.fconv-float/dict.en.th7',
  '-targetdict',
  '/root/wmt14.en-fr.fconv-float/dict.fr.th7',
  '-beam',
  '5',
  '-input',
  '-' ]
```

**Comment by jgehring** [comment]
This is theoretically possible since the BPE tokens are shared across both languages for the pre-trained models. Also, keep in mind that the usage of a BPE vocabulary for the pre-trained models makes them unable to handle unknown words since it hasn't seen any in the training data. In your case, 2 of 5 tokens are unknown words so it's understandable that the model produces seemingly random output.

Did you verify that you're correctly applying the BPE tokenization before feeding the source text to generate-lines? I'm getting the following translations:
- "for me ," -> "pour moi ,"
- "no@@ body pr@@ ay for me ," -> "personne ne prie pour moi ,"

**Comment by loretoparisi** [comment]
@jgehring I guess the problem in this case was the BPE. How do I apply it the the input text?

**Comment by jgehring** [comment]
You can run [apply_bpe.py](https://github.com/rsennrich/subword-nmt/blob/master/apply_bpe.py) and and use the `bpecodes` file in the pre-trained model directory for the `--codes` argument.

**Comment by loretoparisi** [comment]
@jgehring Assumed I have understood the BPE, it should be the same if I'm going to use this one from OpenNMT: https://github.com/OpenNMT/Tokenizer/blob/7c6e2cbad6ce9352a2fdd940faddc1e783db98eb/include/onmt/Tokenizer.h

since they provide a handy executable file in this repo https://github.com/OpenNMT/CTranslate
Is that correct?

**NOTE.**
To be specific, those two cli utils are `tokenize` and `detokenize`, C++ compiled (Boost) libs used by OpenNMT for BEP tokenization/detokenization:

```
[loretoparisi@:mbploreto cli]$ ./tokenize
[loretoparisi@:mbploreto cli]$ ./tokenize --help
Tokenization:
  --help                     display available options
  --mode arg (=conservative) Define how aggressive should the tokenization be: 
                             'aggressive' only keeps sequences of 
                             letters/numbers, 'conservative' allows mix of 
                             alphanumeric as in: '2,000', 'E65', 'soft-landing'
  --joiner_annotate          include joiner annotation using 'joiner' character
  --joiner arg (=￭)        character used to annotate joiners
  --joiner_new               in joiner_annotate mode, 'joiner' is an 
                             independent token
  --case_feature             lowercase corpus and generate case feature
  --bpe_model arg            path to the BPE model

[loretoparisi@:mbploreto cli]$ ./detokenize --help
Detokenization:
  --help                display available options
  --joiner arg (=￭)   character used to annotate joiners
  --case_feature        first feature is the case
```

Thank you.

**Comment by jgehring** [comment]
I've never used CTranslate and couldn't find any information about the BPE code format that it expects from a first glance. Maybe just give it a try and compare the result to `apply_bpe.py`?

**Comment by loretoparisi** [comment]
@jamesgpearce Yes it makes sense, I will try both and update here.
