### ISSUE TITLE
bad argument #2 to 'narrow'

### ISSUE THREAD

**Issue by phveneno** [facebookresearch/fairseq-lua#46]
Hi
I am training a model using wmt en-fr data. I meet a error.  
/home/work/liuhongyu/torch/torch/install/bin/luajit: ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 1 callback] ...ch/torch/install/share/lua/5.1/fairseq/torchnet/data.lua:41: bad argument #2 to 'narrow' (out of range at /home/work/liuhongyu/torch/torch/pkg/torch/lib/TH/generic/THTensor.c:368)
stack traceback:
        [C]: in function 'narrow'
        ...ch/torch/install/share/lua/5.1/fairseq/torchnet/data.lua:41: in function 'makeInput'
        ...ch/torch/install/share/lua/5.1/fairseq/torchnet/data.lua:594: in function 'get'
        .../install/share/lua/5.1/torchnet/dataset/batchdataset.lua:120: in function 'get'
        ...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:110: in function <...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:109>
        [C]: in function 'xpcall'
        ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        ...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        ...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
        [C]: in function 'error'
        ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        ...are/lua/5.1/torchnet/dataset/paralleldatasetiterator.lua:150: in function 'loop'
        ...stall/share/lua/5.1/torchnet/dataset/datasetiterator.lua:107: in function 'next_from_base'
        ...hare/lua/5.1/fairseq/torchnet/ShardedDatasetIterator.lua:102: in function 'loop'
        ...stall/share/lua/5.1/torchnet/dataset/datasetiterator.lua:107: in function 'gloop'
        ...hare/lua/5.1/fairseq/torchnet/SingleParallelIterator.lua:47: in function <...hare/lua/5.1/fairseq/torchnet/SingleParallelIterator.lua:43>
        [C]: in function 'xpcall'
        ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        ...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:65: in function <...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        ...ngyu/torch/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:15: in main chunk
stack traceback:
        [C]: in function 'error'
        ...yu/torch/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        ...hare/lua/5.1/fairseq/torchnet/SingleParallelIterator.lua:63: in function '(for generator)'
        ...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:320: in function 'doTrain'
        ...hare/lua/5.1/fairseq/torchnet/ResumableDPOptimEngine.lua:189: in function 'train'
        ...ch/torch/install/share/lua/5.1/fairseq/scripts/train.lua:405: in main chunk
        [C]: in function 'require'
        ...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
        [C]: at 0x00406820

I can run the training using wmt en-de data. Is there something wrong with the data preprocess? or some thing else.

**Comment by jgehring** [comment]
Just for reference, how did you solve this one?

**Comment by phveneno** [comment]
After I post the issue, I found something wrong with the data after using BPE.  So I close this.

But after I fix it, the entire data (12M lines) is still not working. but the top 6M (half of the entire data) data seems work fine. 

I will run some test. a) using the entire data, but not BPE, b) test the rest 6M  data.  and post the result here.

I guess there is something conflict with BPE and the fairseq preprocess...

**Comment by matthias-samwald** [comment]
I just ran into precisely the same issue with my own data (without BPE preprocessing, but I don't think this has anything to do with it anyways). Any ideas of what might be a cause for this?

**Comment by jgehring** [comment]
Can you double-check that your training data does not contain empty lines in the target language?

**Comment by matthias-samwald** [comment]
Found empty lines, fixed that, running smoothly now!
