### ISSUE TITLE
How to do BPE learn and apply?

### ISSUE THREAD

**Issue by cozec** [facebookresearch/fairseq-lua#49]
"This model uses a Byte Pair Encoding (BPE) vocabulary, so we'll have to apply the encoding to the source text." 

I couldn't find it in the 'Data Pre-processing' section. 

In one of the pre-trained model:
"- We use a BPE sub-word vocublary with 40k tokens, trained jointly on the
  training data for both languages (see bpecodes)"

Do you guys use similar approach like Google's seq2seq? 

thanks.

**Comment by jgehring** [comment]
You can use [subword-nmt](https://github.com/rsennrich/subword-nmt) for learning and applying BPE. This is the same technique as the one described at https://google.github.io/seq2seq/nmt/#data-format .

**Comment by cozec** [comment]
thanks for the reply. Just want to be clear, there is no such step in your example section of "Data Pre-processing:

$ cd data/
$ bash prepare-iwslt14.sh
$ cd ..
$ TEXT=data/iwslt14.tokenized.de-en
$ fairseq preprocess -sourcelang de -targetlang en \
  -trainpref $TEXT/train -validpref $TEXT/valid -testpref $TEXT/test \
  -thresholdsrc 3 -thresholdtgt 3 -destdir data-bin/iwslt14.tokenized.de-en

If I want to apply BPE,  it should be after "prepare-iwslt14.sh" and before "fairseq preprocess"?

thanks again.

**Comment by michaelauli** [comment]
No, we did not detail those steps because they are not strictly required to train a model. You want to apply the BPE tokenization before "fairseq preprocess".
