### ISSUE TITLE
how to require the local lua file, not the installed one.

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/fairseq-lua#53]
```
package.path = package.path .. ';/path/to/fairseq/fairseq/?.lua'
--require 'fairseq'
```
does not work.

**Comment by guotong1988** [comment]
the error:
```
/home/gt/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <Dictionary>
```

**Comment by guotong1988** [comment]
the solution:
`luarocks remove fairseq`

**Comment by guotong1988** [comment]
I could run it in zbstudio. But still get error `module 'fairseq' not found:No LuaRocks module found for fairseq` outside (`th train.lua`).

**Comment by jgehring** [comment]
I'm not sure how zbstudio works. I assume you installed fairseq via luarocks and you can run `fairseq help` from your shell, for example?

**Comment by guotong1988** [comment]
you misunderstand. I want to run it without install it into lua lib

**Comment by guotong1988** [comment]
require `Dictionary` inside the threads

**Comment by jgehring** [comment]
You mean requiring Dictionary helped fixing this? Which thread are you referring to?

**Comment by guotong1988** [comment]
require `Dictionary` before the line of `torch/install/share/lua/5.1/torch/File.lua` which use `Dictionary`
