### ISSUE TITLE
Training visualization?

### ISSUE THREAD

**Issue by smolendawid** [facebookresearch/fairseq-lua#56]
Is there any possibility to visualize word-embeddings, train and test loss, or another parameters of the network?

**Comment by jgehring** [comment]
For training and testing loss, you should be able to parse the log and plot the relevant curves. If needed, training loss can be logged more frequently by passing a lower value to `-log_interval`.

We typically inspect the network's parameters during training by inserting debug layers into the network graph, e.g. via [mutils.makeDebug](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/utils.lua#L43). Again, this amounts to parsing the program output.

There's no built-in functionality to visualize embeddings, but it should be relatively straightforward to dump the learned source and target lookup tables of a model and then use an external program like t-SNE to visualize them.

With a bit of additional code, some of this could be done automatically during training with [visdom](https://github.com/facebookresearch/visdom) (which is also used for attention visualization in `generate-lines`). PRs would be very welcome :)
