### ISSUE TITLE
I try to run it in docker, but get error.

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/fairseq-lua#58]
I set a lot of value for `package.path` and `LUA_PATH`.
But finally can not solve this error.
`FATAL THREAD PANIC: (read) /root/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <Dictionary>`

The src code are mount into docker and the lib are installed in docker image.

**Comment by jgehring** [comment]
It seems that fairseq is not installed correctly. What command did you run? Are you able to launch `th` and execute `require fairseq`?

**Comment by guotong1988** [comment]
you misunderstand. I want to run it without install it into lua lib

**Comment by guotong1988** [comment]
require `Dictionary` inside the threads
