### ISSUE TITLE
How to use fairseq on lua5.2

### ISSUE THREAD

**Issue by ghost** [facebookresearch/fairseq-lua#68]
fairseq uses tds and nccl, and works with luajit.
When using lua5.2, you have to fix two issues in tds, and nccl as follows:

- fix Vec.sort bug in tds, or replace it to table.sort
- make errcheck() returned with 0 in nccl/init.lua

I fixed them, and it works now smoothly.
It will help to solve the issues #33 , and #55.
Here is a small code snippet which I have done.

_fairseq/text/Dictionary.lua_
```
function Dictionary:spairs(t, order)
  local values = {}
  for k,v in ipairs(t) do values[#values+1] = v end

  table.sort(values, function(i, j)
    local idxi = self.symbol_to_index[i]
    local idxj = self.symbol_to_index[j]
    if idxi <= self.nspecial or idxj <= self.nspecial then
      return idxi < idxj
    end
    return self.index_to_freq[idxi] > self.index_to_freq[idxj]
  end)

  local i = 0
  return function()
      i = i + 1
      if values[i] then
        return i, values[i]
      end
  end
end
```
**The new sort function should be replaced with sort() in Dictionary:finalize()**

_nccl/init.lua_
```
local res = nccl.C[name](...)
if res == 0 then return res end
if res ~= 'ncclSuccess' then
...
end
```

This is just a trick to fix it. ;)

**Comment by jgehring** [comment]
Thanks for the info!
