### ISSUE TITLE
multigpu scale up

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#72]
Hi 
I have a question related to multi-GPU scale up. Currently, I change the decoder part of the model/blstm_model.py. I have seen it is faster with multi-GPU setup. However, I encounter an out of memory problem on multi-GPU setting. Originally it takes 5 GB on a single GPU. When I use multi-GPUs, it takes up to12GB on each GPU (then out of memory). It doesn't happen on the codes you released. 
I wonder whether you can give me some advice or suggestions on things I need to be aware. I know it is a bit not clear, but I hope if you have some insights on this topic. Thanks!

**Comment by michaelauli** [comment]
Please paste the exact commands you used for the single and multi-gpu setup.

**Comment by posenhuang** [comment]
`th train.lua -sourcelang de -targetlang en -datadir data-bin/iwslt14.tokenized.de-en   -model XXX -nhid 512 -dropout 0.2 -dropout_hid 0 -optim adam -lr 0.0003125 -savedir trainings/XXX`

The only difference is the `CUDA_VISIBLE_DEVICES`. I think it might be some problems for my code. I'll look into it more.

**Comment by posenhuang** [comment]
Close it for now. As I think it is less related to the repo itself.
