### ISSUE TITLE
question about maxbatch and maxsourcelen

### ISSUE THREAD

**Issue by nikefd** [facebookresearch/fairseq-lua#75]
I used K40 which has 12G memory.
The training data is 1M and the dict size is 40000.
When I set the batch_size = 256 and maxsourcelen = 20, it ran out of memory.
When I set the batch_size = 256 and maxbatch = 256 * 20 = 5120, it work well.
I was feel really confused. What's the difference between them ?
I think if I set  maxsourcelen = 20, then maxbatch will be smaller than 5120, is it right?
Thanks!

**Comment by jgehring** [comment]
`-maxbatch` will check both source and target sequences, while `-maxsourcelen` will only be applied to source sequences. Also, `-maxbatch` works similar to `-bptt` in that if mini-batches exceed the limit, they will be split into smaller batches (along the batchsize dimension). For `-maxsourcelen`, training examples with a source sequence length above the limit will simply be excluded from training.

Regarding your out-of-memory error, do you maybe have some very long target sequences? `-maxsourcelen` is not very useful for controlling memory usage as it will change the amount of training data you're seeing. If your sentences are too long, you should apply a length filter during pre-processing.

**Comment by nikefd** [comment]
I am not really understand.

If I set batchsize = 4 and set maxbatch = 160.  So the step is 40.

And the length of four sentences is 30, 50, 40, 40. We find that 50 is bigger than 40, so the batchsize be halved and become 2 ?
How to deal with the sentences which length is 50, split it to two sentences ?

**Comment by jgehring** [comment]
> If I set batchsize = 4 and set maxbatch = 160. So the step is 40.

What do you mean with step? What is true is that the data provider will only batch 4 sentences together if they don't exceed 40 tokens in length.

> And the length of four sentences is 30, 50, 40, 40. We find that 50 is bigger than 40, so the batchsize be halved and become 2 ?

Yes, exactly. If the 4 sentences in the batch are of length 50 (they always have the same length due to padding), you will get 2 mini-batches, each then consisting of 100 tokens (2*50).

**Comment by nikefd** [comment]
I mean max sentences length. Is it right?
If I get 2 mini-batches, and each consisting 2 * 50, so the sentences length is 50. 
And next batch, the sentences is 40, 40, 40, 40, so the sentences length is 40?
I was confused that the input data of different batch can have different sentences length?
Thanks!

**Comment by jgehring** [comment]
Mini-batches have two dimensions: batch_size (sentences) and sequence length (number of tokens per sentence). The sentences in the training data are naturally of different length, so the data provider adds padding (along the sequence length dimension) to ensure that we have 2-dimensional input. Please note that padding symbols are added to make all sequences in a batch as long as the longest sequence. I.e. if a mini-batch consists of sequences of length 22,34,19,26 (for example), the dimensions after padding are 2*34.

There are several ways to influence the final batch size: `-maxsourcelen` will make sure that (source-side) sequence length will never exceed a given limit by ignoring sequences that are above this limit. `-bptt` will split mini-batches along the sequence length dimension, and `-maxbatch` will split mini-batches along the batch_size dimension.

**Comment by nikefd** [comment]
Does the sequence length of different mini-batch must the same ?
If a mini-batch consists of sequences of length 22,34,19,26 (for example), the dimensions after padding are **4***34 ?

**Comment by nikefd** [comment]
If the network model is create, the input format is fixed, right? So the sequence length of all mini-batch should be set the same, right?

**Comment by jgehring** [comment]
> Does the sequence length of different mini-batch must the same ?
> If the network model is create, the input format is fixed, right? So the sequence length of all mini-batch should be set the same, right?

No, the batch size (both dimensions) is variable.

> If a mini-batch consists of sequences of length 22,34,19,26 (for example), the dimensions after padding are 4*34 ?

Yes. But if the next mini-batch contains sequences of length 10,9,8,10, its dimensions after padding are 10*34.

**Comment by nikefd** [comment]
Oh, I think I should read the paper clearly first and get a clear understanding of your model. I will back if I was lost in your paper haha. Really really thank you!

**Comment by jgehring** [comment]
No worries! If a neural network library supports batching, it will usually allow for variable-sized batches. There are usually some dimensions of the batches that are constant, though, but that depends on the architecture. For the models implemented in fairseq, this would be the embedding dimensions and hidden sizes of the layers. For computer vision models that contain fully-connected layers, the image dimensions might be constant but the number of images you operate on in a single forward/backward pass would be variable.
