### ISSUE TITLE
memory use increase with the dict size increase

### ISSUE THREAD

**Issue by nikefd** [facebookresearch/fairseq-lua#76]
I add a parameter `max_word_vocab_size` in preprocess.lua that I can set the dict size.
I found that when I set dict size = 10000, the GPU cost about 2000M.
When I set the dict size = 40000, the GPU cost about 6000M.
I can't understand what happen.  I think the memory will increase when the dict size increase. But Why the dict size has liner correlation with the memory use? I think the memory should just increase a little.
Thanks.

**Comment by jgehring** [comment]
The dictionary size is usually the biggest factor for memory usage in the model. There are three layers that depend on it (source and target lookup tables and output layer), so with a 40k vocab (and an embedding size of 256) these layers will require `40000 * 256 * 3 * sizeof(float) = 117Mb` of memory (i.e. about 90Mb more than for a 10k vocab) for the parameters, and then the same again for the gradients. If you use an optimizer such as NAG or Adam, you'll get need this one more time for their momentum terms.

**Comment by nikefd** [comment]
You mean that we load the dictionary to the memory many time ?  I am not really understand. Why don't they use the same dictionary?

**Comment by jgehring** [comment]
It's not the dictionary that requires the memory, it's the neural network layers: lookup tables and output layer. We could theoretically share the target and source-side lookup tables if we use the same dictionary, e.g. with a joint BPE vocabulary, but we haven't evaluated how this would affect translation performance.

**Comment by nikefd** [comment]
Ok, got it. Thanks!
