### ISSUE TITLE
BPE usage in the WMT experiments

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#78]
Hi 

1.  In all the WMT experiments, after you build the bpe code using both source and target languages, do you create vocabulary separately (from the pretrained model, it seems that there are dictionary files for both languages)? 
2. Do you create an [alignment file ](https://github.com/facebookresearch/fairseq/blob/master/preprocess.lua#L31)between both vocabularies? 
3. What are the `thresholdsrc` and `thresholdtgt` you used in `fairseq/preprocess`?

Thanks!

**Comment by jgehring** [comment]
Hi @posenhuang!
Re 1: Yes, that's what we do. We simply use BPE for pre-processing and keep everything else the same.
Re 2: Not for the BPE experiments as we do not perform unknown word replacement in this case.
Re 3: For BPE, they are set to 0. For word-based experiments on the WMT, we use `-nwordstgt` and `-nwordssrc` to set the dictionary size explicitly.

**Comment by posenhuang** [comment]
Thanks for your reply!
