### ISSUE TITLE
multiple threads, workers, bptt questions

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#83]
Hi!

We try to add a new model to under fairseq/models/. When we set ndatathreads=1, ngpus=1, we observe something strange. We print a `forward` in the forward function and a `backward` in backward function of the model. In normal cases, we got one `forward` followed by one `backward`. In the error we encounter, there are two `backward` after the `forward`. In the second `backward' part, the size of input is changed. 
I wonder whether something is mixed in multithread, different workers, or bptt such that it tries to do things simultaneously or compute things twice. Thanks!

**Comment by jgehring** [comment]
Hi @posenhuang, I don't think this should happen if you only train on one GPU. The relevant code is [here](https://github.com/facebookresearch/fairseq/blob/cda80d9b51ed054a1df05945c6e82ddf9cd3e508/fairseq/torchnet/ResumableDPOptimEngine.lua#L370-L373). Could you try printing a stack trace in your `forward` and `backward` with `print(debug.traceback())` to check where the second call originates from?

**Comment by posenhuang** [comment]
Thanks @jgehring. I did put a debugger but it is hard to trace since it is nested in the nngraph. I'll look into it again. 
I think my previous description is not perfectly clear. We have a dummy criterion. In the `updateOutput` function, we compute both `forward` and `backward` operations to save some repeated computations. When the model explicitly calls `updateGradInput`, we return a previously computed `gradInput` in the `backward`.  The weird thing is that in a rare case, `forward` is called once but `backward` is called twice. Hence I was thinking whether there are something smart in pipelining or mixing the codes. 
Thanks!

**Comment by posenhuang** [comment]
@jgehring, regarding the multi-threads part. If within my model, part of the model is written in c++ with multiple threads and called by the model in lua. Is there anything I should be aware for the multi-thread usages? 
For some experiments, I couldn't load the intermediate checkpoints back. I got either ``*** Error in `/usr/bin/luajit': realloc(): invalid next size: 0x00007effb4076090 ***`` or ``Segmentation Fault`` in loading the checkpoints. Any thoughts? Thanks a lot!

**Comment by jgehring** [comment]
Hey @posenhuang, sorry for the long delay here. Did you resolve this yet or is this still an issue?

**Comment by posenhuang** [comment]
I think the issue is related to out of memory usage. I'll close the issue. Thanks for checking!
