### ISSUE TITLE
Handling Non-Latin Script

### ISSUE THREAD

**Issue by danpechi** [facebookresearch/fairseq-lua#84]
Hi, I'm trying to run fairseq on mainly Russian data in Cyrillic and am running fairseq preprocess on the proper files. Based on the percentage of tokens replaced by unknown (95%), it seems that the system may not be able to take in Cyrillic. If this is the case, should I transliterate my Cyrillic text and then pass it into fairseq preprocess or is there a way I could modify fairseq to take raw Cyrillic input?

**Comment by jgehring** [comment]
Hi @danpechi, sorry for the delay here. Have you been able to solve this?

**Comment by danpechi** [comment]
Hi Jonas! I was able to resolve this issue.
