### ISSUE TITLE
i can not load the dict.en.th7,what is the structure of the dict.en.th7 file

### ISSUE THREAD

**Issue by linhanxiao** [facebookresearch/fairseq-lua#85]
file=torch.load('dict.en.th7')
the result is

/home/linhanxiao/torch/install/bin/luajit: /home/linhanxiao/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <Dictionary>
stack traceback:
	[C]: in function 'error'
	/home/linhanxiao/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/home/linhanxiao/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load

**Comment by jgehring** [comment]
You will need to require the fairseq module before loading the dictionary file. The `.th7` files are produced with `torch.save()`, but when you call `torch.load()` the class definitions must be available.

**Comment by linhanxiao** [comment]
thanks for your answer
