### ISSUE TITLE
How to generate dict.<language>.th7

### ISSUE THREAD

**Issue by laiviet** [facebookresearch/fairseq-lua#86]
Dear all,

I got following problem:

/home/vietld/torch/install/bin/luajit: cannot open <data/LDC2014.snt-amr/dict.amr.th7> in mode r  at /home/vietld/torch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7ff76b917460
	[C]: in function 'DiskFile'
	/home/vietld/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	...ld/torch/install/share/lua/5.1/fairseq/scripts/train.lua:140: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50

It happenned because of lacking of dict.amr.th7. However, how can I generate that dictionary from corpus. WHat is the format of that file.?

Many thanks,
Lai VIet

**Comment by danpechi** [comment]
Hi Lai, you can generate that dictionary from a parallel aligned corpus. I've modified the prepare-iwslt14.sh script to work for a folder of your choosing where you should load your corpi. Here's the script as a .txt
[prepare-rus.sh.txt](https://github.com/facebookresearch/fairseq/files/1191802/prepare-rus.sh.txt)

**Comment by laiviet** [comment]
Thanks,
It helps forward my job alot.
When I try to translate one sentence into another language using trained model.
 fairseq generate-lines -sourcedict $DATA_DIR/dict.snt.th7 \
                       -targetdict $DATA_DIR/dict.amr.th7 \
                       -path $SAVE_DIR/model_best.th7 \
                       -beam 5 \
                       -nbest 2 \
                       -input $DATA_DIR/test.snt

Then I got following error:
| [target] Dictionary: 6238 types
| [source] Dictionary: 5983 types
/home/vietld/torch/install/bin/luajit: ...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:93: bad argument #2 to 'isatty' (FILE* expected, got nil)
stack traceback:
	[C]: in function 'isatty'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:93: in function 'loop'
	...stall/share/lua/5.1/torchnet/dataset/datasetiterator.lua:107: in function '(for generator)'
	...install/share/lua/5.1/fairseq/scripts/generate-lines.lua:216: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405d50


I am not familiar with torch and lua, Please help me. Thank you.
Lai Viet
