### ISSUE TITLE
Converting state checkpoint to model checkpoint?

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#88]
Hi 

Is there a way to convert a state checkpoint to a model checkpoint? For some reasons, the model checkpoint is not serialized correctly (I cannot load it back on the same machine.). But I can load state checkpoint. I assume the state checkpoint has more information than the model checkpoint, right? 
Thanks a lot!

**Comment by michaelauli** [comment]
You can load the state checkpoint in the trainer (+ specify the model architecture) and then simply save the resulting model as in https://github.com/facebookresearch/fairseq/blob/master/fairseq/torchnet/hooks.lua#L359 and https://github.com/facebookresearch/fairseq/blob/master/fairseq/torchnet/ResumableDPOptimEngine.lua#L248-L260

You can probably do this with a script such as this one or just modify the trainer: https://github.com/facebookresearch/fairseq/blob/master/scripts/make_fconv_vocsel.lua

**Comment by posenhuang** [comment]
Thanks @michaelauli. I'll give it a try.
