### ISSUE TITLE
Using fairseq to train for a general seq2seq task

### ISSUE THREAD

**Issue by iamsimha** [facebookresearch/fairseq-lua#9]
Hi,

is it possible to give list of tensors as input to fairseq torch code?

Ex : Input -> list of tensors
       output -> list of tensors

Will I be able to accomplish the above task using fairseq? If so, can you please point me to a example?

Thanks

**Comment by jgehring** [comment]
Yes, but you'll need to write some Lua code for this. Check out the `generate-lines.lua` script; it has a [data iterator](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L108) that goes from text to tensor to [actual model input](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L108) and then calls [model:generate()](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L218) to do the actual translation. Please let me know if you have further questions.

**Comment by mahmdd** [comment]
facebook
