### ISSUE TITLE
code understanding

### ISSUE THREAD

**Issue by linhanxiao** [facebookresearch/fairseq-lua#90]
ResumableDPOptimEngine.evaluate = argcheck{evaa
    {name='self', type='tnt.ResumableDPOptimEngine'},
    call = function(self)
           print('self:executeAll(function(id) _G.model:network():evaluate() end)')
            self:executeAll(function(id) _G.model:network():evaluate() end)
    end
}
what is the purpose of the code-------_G.model:network():evaluate()

**Comment by michaelauli** [comment]
It puts the model into test mode instead of training mode, see https://github.com/torch/nn/blob/master/doc/module.md#evaluate

**Comment by linhanxiao** [comment]
thanks for your answer
