### ISSUE TITLE
TBC Module Configuration

### ISSUE THREAD

**Issue by danpechi** [facebookresearch/fairseq-lua#92]
Hi,

I'm training my own model and have everything good to go up until I get to this step:
`fairseq preprocess -sourcelang de -targetlang en \
  -trainpref $TEXT/train -validpref $TEXT/valid -testpref $TEXT/test \
  -thresholdsrc 3 -thresholdtgt 3 -destdir data-bin/iwslt14.tokenized.de-en`

I get the following error:
`THCudaCheck FAIL file=/home/dpechi/torch/extra/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
not found: TemporalConvolutionTBC_updateOutput_Cuda
not found: TemporalConvolutionTBC_updateGradInput_Cuda
not found: TemporalConvolutionTBC_accGradParameters_Cuda
not found: TemporalConvolutionTBC_updateOutput_CudaDouble
not found: TemporalConvolutionTBC_updateGradInput_CudaDouble
not found: TemporalConvolutionTBC_accGradParameters_CudaDouble
`
That line in the THCGeneral.c is as follows:
`THCudaCheck(cudaGetDeviceCount(&numDevices));
`

I made sure I had the TBC rock downloaded, but am otherwise uncertain of how to proceed. Upon checking the TBC github, I found that there were functions such as accGradParameters and updateGradInput, however I didn't see anything specific for Cuda or CudaDouble. Is there a separate TBC build I should be using or other way to configure this module with fairseq?

**Comment by michaelauli** [comment]
Please try to rebuild the TBC convolution and then check that you can create a nn.TemporalConvolutionTBC in a REPL.

**Comment by jgehring** [comment]
This looks like it has been resolved. Please re-open if necessary.
