### ISSUE TITLE
fail to optimize for generation speed

### ISSUE THREAD

**Issue by zhenbiaochen** [facebookresearch/fairseq-lua#93]
fairseq optimize-fconv -input_model ./trainings/zh2en/model_best.th7 -output_model ./trainings/zh2en/model_best_opt.th7
/mnt/data/install/torch/install/bin/luajit: ...install/share/lua/5.1/fairseq/scripts/optimize-fconv.lua:25: "FConvModel" expected
stack traceback:
	[C]: in function 'error'
	...install/share/lua/5.1/fairseq/scripts/optimize-fconv.lua:25: in main chunk
	[C]: in function 'require'
	...rch/install/lib/luarocks/rocks/fairseq/scm-1/bin/fairseq:17: in main chunk
	[C]: at 0x00405e90

**Comment by nikefd** [comment]
hi, @zhenbiaochen , is the model_best.th7 a FConvModel ?

**Comment by zhenbiaochen** [comment]
no ， the model model_best.th7 is blstm model.
could  just FConvModel to  speed up for cpu ?

**Comment by nikefd** [comment]
I am not really sure, but the file `optimize-fconv.lua` is just for FConvModel, you can look at the code in `optimize-fconv.lua` and `fconv_model.lua->FConvModel.makeDecoderFast` for what it is done for speed up.

**Comment by jgehring** [comment]
@nikefd is correct, `optimize-fconv` requires a `fconv` model as indicated by the error message.

**Comment by negacy** [comment]
I am having similar issue for an fconv model, as shown blow. 

> git/torch/install/bin/luajit: ...install/share/lua/5.1/fairseq/scripts/optimize-fconv.lua:25: "FConvModel" expected
> stack traceback:
> 	[C]: in function 'error'
> 	...install/share/lua/5.1/fairseq/scripts/optimize-fconv.lua:25: in main chunk
> 	[C]: in function 'require'
> 	...install/lib/luarocks/rocks/fairseq-cpu/scm-1/bin/fairseq:17: in main chunk
> 	[C]: at 0x00405d50
> 
Here is my script for the training:
```
fairseq train -sourcelang ml \
        -targetlang en \
        -datadir  data/data-bin/mutlilingual \
        -model fconv \
        -nenclayer 4 \
        -nlayer 3 \
        -dropout 0.2 \
        -optim nag \
        -lr 0.25 \
        -clip 0.1 \
        -momentum 0.99 \
        -timeavg \
        -bptt 0 \
        -savedir trainings/fconv \
        -save_interval 100000 \
        -batchsize 32
```
Any help?
