### ISSUE TITLE
question about generation process

### ISSUE THREAD

**Issue by nikefd** [facebookresearch/fairseq-lua#94]
I am confused about the generation process.
I use a pre-trained model to do generation.
`fairseq generate-lines -sourcedict $DATA/dict.de.th7 -targetdict $DATA/dict.en.th7 \
  -path trainings/fconv/model_best_opt.th7 -beam 10 -nbest 2
`
I think the process is as below:
1. [generate-lines.lua#L151](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L151)
```
model = require(
        'fairseq.models.ensemble_model'
    ).new(config)
```
2. [ensemble_model.lua#L32](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/ensemble_model.lua#L32)
`self.models[i] = torch.load(path)`
3. [generate-lines.lua#L218](https://github.com/facebookresearch/fairseq/blob/master/generate-lines.lua#L218)
`local hypos, scores, attns = model:generate(config, sample, searchf)`
4. [ensemble_model.lua#L61](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/ensemble_model.lua#L61)
EnsembleModel.generate function
```
for _, model in ipairs(self.models) do
     table.insert(callbacks, model:generationCallbacks(config, bsz))
end
```
5. [model.lua#L109](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/model.lua#L109)
Model.generationCallbacks function

But I am confused about what generationCallbacks function return and get lost.
Such as generationEncode function, it return nothing.
```
Model.generationEncode = argcheck{
    doc=[[
Returns a function that performs the encoder forward pass.
After that it duplicates the encoder output for each
beam hypotheses.
]],
    {name='self', type='Model'},
    {name='config', type='table'},
    {name='bsz', type='number'},
    call = function(self, config, bsz)
        error('Implementation expected')
    end
}
```

I also confused about the `states`, such as
 [ensemble_model.lua#L100-L113](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/ensemble_model.lua#L100-L113)

```
local states = {}
for i = 1, #self.models do
    states[i] = {
        sample = sample,
    }
end

timers.setup:resume()
local states = {}
for i = 1, #self.models do
    states[i] = callbacks[i].setup(sample)
end
timers.setup:stop()
```
The `states[i] = {sample = sample,} don't be used, right?
Looking forward to your reply, thanks!

**Comment by nikefd** [comment]
I find the implementation is at `fconv_model.lua`, thanks.

**Comment by nikefd** [comment]
I can't find what the implementation of `Model.generationEncode` in `fconv_model.lua` and `model.lua`.

**Comment by jgehring** [comment]
`FConvModel` is actually a subclass of `AvgpoolModel`, specifically because it shares some of these utility functions. The inherited implementation of `generationEncode` is [here](https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/avgpool_model.lua#L344).

**Comment by nikefd** [comment]
Oh, got it. Thanks!
