### ISSUE TITLE
how to use pre-training word embedding

### ISSUE THREAD

**Issue by wubin1836** [facebookresearch/fairseq-lua#95]
I think this work is very interesting and meaningful, but because of the lack of parallel corpus in the machine translation task.
Word embedding, which was trained by a single corpus, can be used as an initialization to improve the translation effectively. Can the work use Pre training embedding. If so, how should I initialize it?

**Comment by michaelauli** [comment]
Sure, you need to set the weight tensor of the lookup tables and/or the
linear for the final output layer with the pre-trained embeddings.

**Comment by wubin1836** [comment]
Thanks a lot !

**Comment by ykl7** [comment]
@michaelauli @wubin1836 can you please provide some pointers on this?
