### ISSUE TITLE
Contributing pretrained models (wmt17.zh-en)

### ISSUE THREAD

**Issue by twairball** [facebookresearch/fairseq-lua#97]
Hi guys,

I'd like to contribute my models i've trained on wmt17 news commentary for chinese-english. 

Are there any guidelines on dataset? I randomly split dataset 80% training 10% validation 10% test. 

(website mentions they don't have preprocessed training or dev sets for zh-en) 
http://www.statmt.org/wmt17/translation-task.html

- [wmt17.zh-en.fconv-cuda](https://s3-us-west-2.amazonaws.com/twairball.wmt17.zh-en/wmt17.zh-en.fconv-cuda.tgz): Pre-trained model for [WMT17 Chinese-English](http://www.statmt.org/wmt17/translation-task.html) 
- [wmt17.zh-en.fconv-float](https://s3-us-west-2.amazonaws.com/twairball.wmt17.zh-en/wmt17.zh-en.fconv-float.tgz): CPU version of the above

|Model | Epochs | Training Time | BLEU4 (beam1) | BLEU4 (beam5) | BLEU4 (beam10) | BLEU4 (beam20)|
|------|--------|---------------|---------------|---------------|----------------|---------------|
| fconv | 25 | ~2hrs | 63.49 | 62.22 | 62.52 | 62.74 |
| blstm | 30 | ~8hrs | 64.59 | 64.15 | 64.38 | 63.76 |
| convenc | 47 | ~7hrs | 50.91 | 56.71 | 56.83 | 53.66 |

(Comment edited with links to models and training results)

**Comment by michaelauli** [comment]
Thanks! Before adding the model, please add a README.md similar to the other pretrained models (https://github.com/facebookresearch/fairseq#pre-trained-models) describing the data pre-processing. Each archive also contains source/target dictionaries as well as an optional bpe code file (if the data was bpe encoded), e.g.,

$ ls wmt16.en-ro.fconv-float
bpecodes  dict.en.th7  dict.ro.th7  model.th7  README.md

**Comment by twairball** [comment]
Thanks for the reply michael -- I'll fix that up soon.

**Comment by neoyang0620** [comment]
Hi,
the link contains pretrained-models doesn't work. Could you please give me another valid link?
