### ISSUE TITLE
How can I train based on the good model?

### ISSUE THREAD

**Issue by zero4he** [facebookresearch/fairseq-lua#98]
I have trained a good model, but now I have more corpus, how can I train based on the original model?

**Comment by jgehring** [comment]
If I understand your question correctly, you want to fine-tune one of the pre-trained models that we provide on your own data? In `train.lua` you can find a function that's called `make_model_fn`. You could alter this method to load an existing model instead of creating a new one.

**Comment by jgehring** [comment]
Has this been resolved?

**Comment by zero4he** [comment]
Thank you. I've solved it.
